[package]
name = "arcturus-prime/hive"
version = "0.1.16"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A compact library for interfacing with Actors"

[dependencies]
